name: community_manager

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_media_001_development
    ports:
      - "5432:5432"
    networks:
      - app_network

  web:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/social_media_001_development
      # DATABASE_URL: postgres://postgres:postgres@db:5432/social_media_001_test
      DOCKER: "true"
      # RAILS_ENV: test
      RAILS_ENV: development
    networks:
      - app_network
  
  selenium:
    image: selenium/standalone-chrome:120.0
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_VNC_PASSWORD=test123
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: