name: community_manager

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_media_001_development
    ports:
      - "5432:5432"
    networks:
      - app_network

  web:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/social_media_001_development
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: